branch-defaults:
  default:
    environment: null
    group_suffix: null
global:
  application_name: staying-sharp
  default_ec2_keyname: null
  default_platform: 64bit Amazon Linux 2016.03 v2.1.1 running Node.js
  default_region: us-west-2
  profile: null
  sc: null
