Encoding:
  Enabled: false

Documentation:
  Enabled: false

ClassAndModuleChildren:
  Enabled: false

ClassLength:
  Enabled: false

MethodLength:
  Enabled: false

DoubleNegation:
  Enabled: false

ModuleLength:
  Exclude:
    - "spec/**/*"

AllCops:
  Exclude:
    - "bin/**/*"
    - "db/**/*"
    - "config/**/*"
    - "Rakefile"
    - "spec/i18n_spec.rb"
    - "client/**/*"
    - "node_modules/**/*"
    - "app/services/import_content/process_activity_json.rb"
    - "app/services/import_content/process_recipe_json.rb"
    - "app/jobs/import_content_item_job.rb"
    - "lib/tasks/data_migration.rake"
